# Generated by Django 5.0.2 on 2025-03-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='counytry_code',
            new_name='country_code',
        ),
    ]
